.TH XIL\-INIT "1" "2026\-04\-05" "xil\-pipeline 0.1.3" "User Commands"
.SH NAME
xil\-init
.SH SYNOPSIS
.B xil\-init
[-h] [--show SHOW] [--season SEASON] [--season-title TITLE] [directory]
.SH DESCRIPTION
Scaffold a new xil\-pipeline project workspace

.TP
\fBdirectory\fR
Target directory (default: current directory)

.SH OPTIONS
.TP
\fB\-\-show\fR \fI\,SHOW\/\fR
Show name for project.json (default: "Sample Show")

.TP
\fB\-\-season\fR \fI\,SEASON\/\fR
Season number for project.json and the sample script header

.TP
\fB\-\-season\-title\fR \fI\,TITLE\/\fR
Season/arc title for project.json and the sample script header

.SH SEE ALSO
.BR xil (1),
.BR xil-scan (1),
.BR xil-parse (1),
.BR xil-cues (1),
.BR xil-produce (1),
.BR xil-assemble (1),
.BR xil-daw (1),
.BR xil-migrate (1),
.BR xil-cleanup (1),
.BR xil-import (1),
.BR xil-regen (1),
.BR xil-master (1),
.BR xil-voices (1),
.BR xil-csv-join (1),
.BR xil-sfx (1),
.BR xil-sample (1),
.BR xil-sfx-lib (1),
.BR xil-splice (1),
.BR xil-mp3-hash (1),
.BR xil-init (1)
.SH AUTHOR
John Brissette <xilcmd@gmail.com>
