.TH XIL\-SCAN "1" "2026\-04\-05" "xil\-pipeline 0.1.3" "User Commands"
.SH NAME
xil\-scan
.SH SYNOPSIS
.B xil\-scan
[-h] [--json] [--speakers SPEAKERS] path
.SH DESCRIPTION
Pre\-flight scanner: check a production script for unknown speakers/sections.

.TP
\fBpath\fR
Path to the markdown production script

.SH OPTIONS
.TP
\fB\-\-json\fR
Output machine\-readable JSON instead of the human report

.TP
\fB\-\-speakers\fR \fI\,SPEAKERS\/\fR
Path to speakers.json (default: auto\-detect from CWD, then built\-in)

.SH SEE ALSO
.BR xil (1),
.BR xil-scan (1),
.BR xil-parse (1),
.BR xil-cues (1),
.BR xil-produce (1),
.BR xil-assemble (1),
.BR xil-daw (1),
.BR xil-migrate (1),
.BR xil-cleanup (1),
.BR xil-import (1),
.BR xil-regen (1),
.BR xil-master (1),
.BR xil-voices (1),
.BR xil-csv-join (1),
.BR xil-sfx (1),
.BR xil-sample (1),
.BR xil-sfx-lib (1),
.BR xil-splice (1),
.BR xil-mp3-hash (1),
.BR xil-init (1)
.SH AUTHOR
John Brissette <xilcmd@gmail.com>
