.TH XIL\-MIGRATE\-WORKSPACE "1" "2026\-04\-19" "xil\-pipeline 0.1.8" "User Commands"
.SH NAME
xil\-migrate\-workspace
.SH SYNOPSIS
.B xil\-migrate\-workspace
[-h] [--workspace WORKSPACE] [--dry-run]
.SH DESCRIPTION
Migrate a pre\-0.1.8 workspace to the normalized directory layout

.SH OPTIONS
.TP
\fB\-\-workspace\fR \fI\,WORKSPACE\/\fR
Workspace root directory (default: current directory)

.TP
\fB\-\-dry\-run\fR
Preview moves without touching files (default: enabled for safety)

.SH SEE ALSO
.BR xil (1),
.BR xil-scan (1),
.BR xil-parse (1),
.BR xil-cues (1),
.BR xil-produce (1),
.BR xil-assemble (1),
.BR xil-daw (1),
.BR xil-migrate (1),
.BR xil-cleanup (1),
.BR xil-import (1),
.BR xil-regen (1),
.BR xil-master (1),
.BR xil-voices (1),
.BR xil-csv-join (1),
.BR xil-sfx (1),
.BR xil-sample (1),
.BR xil-sfx-lib (1),
.BR xil-splice (1),
.BR xil-mp3-hash (1),
.BR xil-migrate-workspace (1),
.BR xil-init (1)
.SH AUTHOR
John Brissette <xilcmd@gmail.com>
