.TH XIL\-INIT "1" "2026\-07\-27" "xil\-pipeline 0.3.2" "User Commands"
.SH NAME
xil\-init
.SH SYNOPSIS
.B xil\-init
[-h] [--show SHOW] [--type {podcast,audiobook,drama,special}] [--season SEASON] [--season-title TITLE] [--flat] [--no-flat] [directory]
.SH DESCRIPTION
Scaffold a new xil\-pipeline project workspace

.TP
\fBdirectory\fR
Target directory (default: XIL_PROJECTROOT if set, else current directory)

.SH OPTIONS
.TP
\fB\-\-show\fR \fI\,SHOW\/\fR
Show name for project.json (default: "Sample Show")

.TP
\fB\-\-type\fR \fI\,{podcast,audiobook,drama,special}\/\fR
Content type: podcast (default), audiobook, drama, special

.TP
\fB\-\-season\fR \fI\,SEASON\/\fR
Season number for project.json and the sample script header

.TP
\fB\-\-season\-title\fR \fI\,TITLE\/\fR
Season/arc title for project.json and the sample script header

.TP
\fB\-\-flat\fR
Use multi\-show flat layout: project.json in configs/{slug}/, per\-show category
subdirs (default)

.TP
\fB\-\-no\-flat\fR
Use legacy single\-show layout: all dirs at workspace root

.SH SEE ALSO
.BR xil (1),
.BR xil-scan (1),
.BR xil-parse (1),
.BR xil-cues (1),
.BR xil-produce (1),
.BR xil-assemble (1),
.BR xil-studio-onboard (1),
.BR xil-daw (1),
.BR xil-migrate (1),
.BR xil-cleanup (1),
.BR xil-import (1),
.BR xil-regen (1),
.BR xil-master (1),
.BR xil-voices (1),
.BR xil-csv-join (1),
.BR xil-sfx (1),
.BR xil-sample (1),
.BR xil-sfx-lib (1),
.BR xil-splice (1),
.BR xil-mp3-hash (1),
.BR xil-stem-log (1),
.BR xil-migrate-workspace (1),
.BR xil-remove-show (1),
.BR xil-remove-episode (1),
.BR xil-status (1),
.BR xil-sfx-restore (1),
.BR xil-db-profile (1),
.BR xil-sfx-csv (1),
.BR xil-parsed-csv (1),
.BR xil-sfx-hydrate (1),
.BR xil-episode-summary (1),
.BR xil-stem-verify (1),
.BR xil-stem-compare (1),
.BR xil-publish (1),
.BR xil-gui (1),
.BR xil-use (1)
.SH AUTHOR
John Brissette <xilcmd@gmail.com>
