.TH XIL\-STUDIO\-ONBOARD "1" "2026\-04\-24" "xil\-pipeline 0.1.8" "User Commands"
.SH NAME
xil\-studio\-onboard
.SH SYNOPSIS
.B xil\-studio\-onboard
[-h] (--episode EPISODE | --tag TAG) [--show SHOW] [--dry-run] [--quality {standard,high,ultra,ultra_lossless}] [--model MODEL]
.SH DESCRIPTION
Onboard an episode to an ElevenLabs Studio project.

.SH OPTIONS
.TP
\fB\-\-episode\fR \fI\,EPISODE\/\fR
Episode tag (e.g. S01E02)

.TP
\fB\-\-tag\fR \fI\,TAG\/\fR
Raw tag for non\-episodic content (e.g. V01C03, D01)

.TP
\fB\-\-show\fR \fI\,SHOW\/\fR
Show name override (default: from project.json)

.TP
\fB\-\-dry\-run\fR
Build and display content JSON without calling the API

.TP
\fB\-\-quality\fR \fI\,{standard,high,ultra,ultra_lossless}\/\fR
Quality preset (default: standard)

.TP
\fB\-\-model\fR \fI\,MODEL\/\fR
TTS model ID (default: eleven_v3)

.SH SEE ALSO
.BR xil (1),
.BR xil-scan (1),
.BR xil-parse (1),
.BR xil-cues (1),
.BR xil-produce (1),
.BR xil-assemble (1),
.BR xil-studio-onboard (1),
.BR xil-daw (1),
.BR xil-migrate (1),
.BR xil-cleanup (1),
.BR xil-import (1),
.BR xil-regen (1),
.BR xil-master (1),
.BR xil-voices (1),
.BR xil-csv-join (1),
.BR xil-sfx (1),
.BR xil-sample (1),
.BR xil-sfx-lib (1),
.BR xil-splice (1),
.BR xil-mp3-hash (1),
.BR xil-migrate-workspace (1),
.BR xil-init (1)
.SH AUTHOR
John Brissette <xilcmd@gmail.com>
